version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DB_NAME: postgres
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5632:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      retries: 10
    deploy:
      mode: replicated
      replicas: 1

  init-data:
    image: ghcr.io/aylinyil/scope-service-initial-data:commit-e98b1ba8bdcb4ea7f9cf2f6653dde2d172193cfc
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
    deploy:
      mode: replicated-job
      replicas: 1
    command: >
      sh -c ' echo "⏳ Waiting for Postgres..."; until pg_isready -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER"; do sleep 2; done; echo "✅ Database ready, starting init process..."; python main.py '
